# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'Marathi Bible ERV' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for English Bible
  pod 'IQKeyboardManagerSwift'
  pod 'Alamofire', '~> 4.7'
  pod 'SideMenu'
  pod 'lottie-ios'
  pod 'Toast-Swift'
  #pod 'SwiftAudio', '~> 0.11.2'
  pod 'SwiftAudioPlayer'
  target 'Marathi Bible ERVTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Marathi Bible ERVUITests' do
    # Pods for testing
  end

end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "14.0"
    end
  end
end
